### ISSUE TITLE
the app freezes when changing the main screen

### ISSUE THREAD

**Issue by dasacom** [javikr/sofatime#20]
**Describe the bug**
when starting and sometimes when using the app the main screen freezes for a few seconds. 
Very disturbing!
(I think it was a little bit better with the last beta)

**To Reproduce**

**Expected behavior**
smooth scrolling

**Screenshots**
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - OS: ios 15.5
 - Using Stable Version from the App Store

**Additional context**

**Comment by javikr** [comment]
Hi @dasacom 

Please check if this bug is fixed in: v2.5.7

Thanks!

**Comment by dasacom** [comment]
It is Not fixed yet. 
running latest beta
Also images loading slower than before.

**Comment by javikr** [comment]
Ok... I see.. Maybe this issue is related with this discussion: https://github.com/javikr/sofatime/discussions/24 ?

**Comment by javikr** [comment]
I'm going to close this issue. We have done some more efforts to fix this issue in the latest update.
