### ISSUE TITLE
Let me choose in the settings the "first page"

### ISSUE THREAD

**Issue by dasacom** [javikr/sofatime#21]
**Is your feature request related to a problem? Please describe.**
When the app starts it is loading the "Discover" page

**Describe the solution you'd like**
It would be great to add in the settings the possibility to choose the starting page.
I would prefer "My lists" to be my home page :-)

**Describe alternatives you've considered**
Alternatives shoud be to choose between: Discover, my lists, calendar and Profile

**Comment by javikr** [comment]
Duplicated
