### ISSUE TITLE
Interactive Widget

### ISSUE THREAD

**Issue by henrymatus** [javikr/sofatime#37]
It would be very very helpful if the widget were interactive so I can tap the chapter that I already seen and qualified from right there and then passes to the next chapter :) 

![image](https://user-images.githubusercontent.com/121219575/209185466-0c3a04fc-5378-4a91-b0fb-a2e642a0abbc.png)

**Comment by javikr** [comment]
Thank you for your support. Please let me investigate if this is possible with the current iOS Widgets

**Comment by javikr** [comment]
As update, just let you know we have this functionality in our roadmap for users using iOS17+

**Comment by javikr** [comment]
It's done.
