### ISSUE TITLE
UP NEXT not updating

### ISSUE THREAD

**Issue by novumus** [javikr/sofatime#38]
Pull down to refresh on "My lists" does not work. The UP NEXT do not get updated, still sees the same series since it last worked. Force quit the app and start it again does not update the UP NEXT. Rebooting the phone don not work either. 

If I mark an episode in the 3 top UP NEXT as seen it is working but if I mark a episode on the Trakt website or in another app it does not update that I have seen them in the Sofa Time app. Even if I go into a series in the app and choose seen on a episode, that series do not show up in UP NEXT. 

If I clear the cache in the app, and force close the app, then the up next gets updated. Also I then see a yellow round popup saying "Updating data... Please wait". But it only works one time, the next time I mark a serie as watched like descibed above I have to clear cache again to make it work.

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: 16.2
 - Browser: Safari
 - Version: 2.7.11 of the Sofa Time app

**Comment by javikr** [comment]
Thank you for your report. We have implemented some changes related with the syncing process that affected directly to the Up Next section. The update 2.7.12 will include some breaking changes that will reduce the syncing time drastically and will fix (I hope) all syncing-related bugs.
