### ISSUE TITLE
Poster showing wrong language

### ISSUE THREAD

**Issue by GuTf843Bu** [javikr/sofatime#39]
**Describe the bug**
Some shows' posters do not show in the correct language (= different from system language or even the show original language)

**To Reproduce**
Go to any list and basically scroll down and you should see some errors. They seem to be random and do not correct themselves after restarting the app. Maybe it doesn't happen to everyone.

**Expected behavior**
The poster should be in the correct language/system language.

**Screenshots**
See attached screenshot and the red circles where the language is wrong.

**Smartphone (please complete the following information):**
 - Device: [iPhone11]
 - OS: [iOS16.2]
 - Version [2.8.1 (300)]

![sofa1](https://user-images.githubusercontent.com/124357154/216894112-a73f52fe-658f-4a66-9ba8-6efd334fb349.jpeg)

**Comment by javikr** [comment]
This issue is fixed. Closing now.
