### ISSUE TITLE
Flexibility to allow different views for each lists

### ISSUE THREAD

**Issue by GuTf843Bu** [javikr/sofatime#40]
**Is your feature request related to a problem? Please describe.**
As of now, if I select the "poster view" in my "watch next" list, the view in my "Upcoming series" will also automatically be switched to the same "poster view" but I would like to be able to choose the type of view for each list. 
Because I'd prefer to have a poster view for my upcoming shows to have an overall view of what's coming (I don't need the details at that point) but a more detailed view (list or card) for a show I'm watching now because I might want to check the comments for this show.

**Describe the solution you'd like**
For example I'd like to be able to assign a view type to each list I consult. For example : poster view for "Watch next" BUT list view for "Upcoming series" AND card view for "Upcoming releases" list

**Describe alternatives you've considered**
Not sure if there is another way.

**Additional context**

**Comment by javikr** [comment]
Thank you for your suggestion. I will keep in mind.

**Comment by javikr** [comment]
You are now be able to choose a different view type for each list. I will close the issue 👍
