### ISSUE TITLE
Remaining episodes icon on posters in Watch next list

### ISSUE THREAD

**Issue by GuTf843Bu** [javikr/sofatime#41]
**Is your feature request related to a problem? Please describe.**
Not absolutely necessary but it would be great to have a number in the upper right corner of the poster of the shows showing the remaining episodes to watch for this show.

**Comment by javikr** [comment]
Done! Please update to v2.8.2
![Image](https://user-images.githubusercontent.com/3273648/220079690-c73c2ee0-2ad0-4a56-a9d0-8ce2bf8423f6.png)
