### ISSUE TITLE
Incorrect and misleading number of episodes left to watch

### ISSUE THREAD

**Issue by kamil-zbroniec** [javikr/sofatime#45]
**Is your feature request related to a problem? Please describe.**
It's not really a big problem, but I find it counterintuitive and sometimes even buggy that the number of episodes left to watch include a plus sign. From what I understand it means that other than the episode that is currently being shown, there are n-more episodes left to watch. So a total number episodes left to watch equals n+1. I think it's fine, but not really great as a number most of the users will be looking for is total number of episodes left (n+1), not total number of episodes except of the next one (n). This description relates to "up next" section and TV series details page. The buggy part is related to "Watch next" page. It shows the same number as on the other screens but without plus sign ("n left"). So it is misleading, as actual value should be "n+1 left" or "n(+) left".

<p float="left">
<img src="https://user-images.githubusercontent.com/41733498/232418113-89ad6235-b9b1-4871-9882-8ab2e1de0d33.jpeg" width="250"/>
<img src="https://user-images.githubusercontent.com/41733498/232418149-254aa2c5-9063-4d77-b8b8-5c7313862aac.jpeg" width="250"/>
<img src="https://user-images.githubusercontent.com/41733498/232418174-e1d7d86c-ff0b-4f6f-8b74-caaad383d1d9.jpeg" width="250"/>
</p>

**Describe the solution you'd like**
I suggest switching to displaying total number of episodes left and ditching the plus sign.

**Comment by javikr** [comment]
Thank you for your report. I like your suggestion. I will update that information to display always the total number of episodes left (including "left" copy). For ex.: "15 left"

**Comment by kamil-zbroniec** [comment]
Great. That's excatly what I had in mind.

**Comment by kamil-zbroniec** [comment]
Which version will contain this change?
