### ISSUE TITLE
Up Next does not sync changes

### ISSUE THREAD

**Issue by holgerh** [javikr/sofatime#46]
**Describe the bug**
The "up next" section does not sync correctly.

**To Reproduce**
1. mark episode in "up next" as seen
2. episode disappears but a red X appears in the middle of the screen
3. mark a new tv show as "begin to watch"
4. go to "up next" and start to sync
5. new tv-show from (2) does not appear in list, but episode from (1) is there again

**Expected behavior**
The watched episode is gone and the new tv-show appears in the "up next" section

**Screenshots**
<img src="https://user-images.githubusercontent.com/39573/232712394-61e83e95-11ff-420d-a214-66a1e7e793aa.jpeg" width=50% height=50%>

**Smartphone (please complete the following information):**
 - Device: iPhone 13 mini
 - OS: 16.4.1
 - App-Version 2.8.9

**Additional context**

**Comment by javikr** [comment]
Hi there!
Please let me know if there is any update on this. We have been working in that section for the last weeks and it should be fixed.
