### ISSUE TITLE
Episodes are marked as watched only for a second, then switched back to unwatched

### ISSUE THREAD

**Issue by kamil-zbroniec** [javikr/sofatime#47]
**Describe the bug**
Most of the time when I open the app after long (eg. several hours) break and try to mark an episode as watched it is being displayed as watched, but after few seconds it is switched back to unwatched. From this moment everything starts working correctly and any additional episodes when marked as watched is kept in this state. See attached video.

**Screenshots**
https://github.com/javikr/sofatime/assets/41733498/81a4ba88-a0ce-436e-97b5-470717f75ba3

**Smartphone:**
 - Device: [iPhone 14 Pro]
 - OS: [iOS 16.5.1]
 - Version [2.10.5 (480) - 6P.N.]

**Comment by dasacom** [comment]
I have the same issue since weeks!

Iphone 11
OS: 16.5.1

**Comment by javikr** [comment]
Thank you for your report. As I can see in the attached video the list is loading when the watched button is tapped. In that case, some issues can appear.

Please let me check how I can prevent that situation.

**Comment by dimyl452** [comment]
Why not prevent from marking as watched while the app is loading, like greyed out.

**Comment by steffen-gs** [comment]
This is still an issue and it's driving me crazy 🥺
Don't you have any idea to fix it?
Put the mark as watched action in a queue and send them when the update process is done or something? The connection with trakt is so slow... so it's taking so long just to mark one episode as watched.

**Comment by javikr** [comment]
This issue should be fixed in the latests updates.
