### ISSUE TITLE
Mark previous episodes as watched? Improvement

### ISSUE THREAD

**Issue by GuTf843Bu** [javikr/sofatime#49]
**Describe the bug**
Let's say I watch a TV show's first episode and I mark it as Watched. The next day, I watch episodes 2 & 3 and when long tap the check icon on ep.3 to mark it Watched, it offers the option to also mark previous episodes (like ep.2) Watched. The issue is that if I choose to do so, it will mark the first episode Watched a second time.

**To Reproduce**
See above.

**Expected behavior**
Either:
1/ just mark as Watched the multiple previous episodes that were never watched
Or
2/ offer the choice "All" or "Unwatched only"

**Screenshots**
None.

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 16.4.1
 - Browser safari

**Comment by javikr** [comment]
Hi there,
This issue is fixed in the latest version (2.35.2)
