### ISSUE TITLE
Behavior after clicking on TV show title on next to watch is different between the app and the widget

### ISSUE THREAD

**Issue by kamil-zbroniec** [javikr/sofatime#53]
**Describe the bug**
Inconsistent behavior while clicking on the TV show title in the app (watch page) and in the widget (next to watch widget). The first one redirects to current season page, the second redirects to the TV show page.

**To Reproduce**
1. Go to Next to watch widget
2. Click on TV show title
3. You are redirected to the TV show page

1. Go to Watch page in the app
2. Click on TV show title
3. You are redirected to the TV show current season page

**Expected behavior**
I think the behavior of the widget is more helpful as I'd rather be redirected to the TV show page, where I can see cast info, show ratings, users comments, etc. instead of being redirected to the season page, which doesn't bring too much to the table.

**Comment by javikr** [comment]
This issue is fixed in the latest version.
