### ISSUE TITLE
Rating is disabled but pops up

### ISSUE THREAD

**Issue by idnovic** [javikr/sofatime#54]
**Describe the bug**
I disabled the episode rating selector. 
I am still greeted with the rating selector after I mark an episode as watched. 

**To Reproduce**
1. Go to watch tab
2. Click on "watched" for a episode
3. Rating selector appears

**Expected behavior**
No rating selector. 
I just like to track what I have watched.

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 17.6

**Comment by javikr** [comment]
Hi there,
Please check if this issue is still happening on the latest version (2.35.1). 

Thank you,
