### ISSUE TITLE
Allow to indicate the viewing time in the “Watched on another date” option

### ISSUE THREAD

**Issue by tzinm** [javikr/sofatime#58]
It's great to have the possibility to set a custom viewing date for both films and show episodes.

This functionality only allows us to indicate the day, month and year. In other words, we cannot indicate the time it was viewed. From what I have seen in other apps where the time of viewing is shown, it seems that the time is set at the time the user has customised the date.

It would be great to be able to indicate the time next to the date, just as you can do in other applications that use Trakt.tv.

The following screenshot illustrates the same "_Watched in another date_" feature of the [Watcht for Trakt](https://apps.apple.com/es/app/watcht-for-trakt/id1396920723) iOS app.

![“Watched in another date” feature in the “Watcht for Trakt” app](https://github.com/user-attachments/assets/ab558b84-6b0c-4616-9634-639c2324894a)

**Comment by javikr** [comment]
This feature is now available :)
