### ISSUE TITLE
Implement spoiler rendering for comments

### ISSUE THREAD

**Issue by tzinm** [javikr/sofatime#60]
**Is your feature request related to a problem? Please describe.**
Currently, comments marked as spoilers using the [spoiler] tags are not rendered correctly in the Sofa Time application. Users can see the opening `[spoiler]` tag, but the actual spoiler content is not displayed.

**Describe the solution you'd like**
I would like the application to render comments with the `[spoiler]` tags properly.

**Describe alternatives you've considered**
Click on the `[spoiler]` tag to reveal the hidden content.

**Additional context**
For reference, here is how a comment with a spoiler (_Season 2 Episode 6 from Modern Love_) is displayed on the Trakt.tv website:

![traktv-spoiler-example](https://github.com/user-attachments/assets/19823f9a-98b5-4457-ad4d-5751e19edb57)

Currently, this is how the same comment appears in the Sofa Time application:

![sofatime-spoiler-example](https://github.com/user-attachments/assets/73b32124-d0e1-46d3-ac36-e151f5f77e6e)

Additionally, here’s an example of how another application that uses Trakt.tv (Watcht) handles spoilers:

https://github.com/user-attachments/assets/39157322-d2e6-43a8-a009-40796da53a3d

**Comment by javikr** [comment]
Hi there! Thank you for your report.

It's a good point. We will start working on this.

**Comment by javikr** [comment]
Closing as this feature is available starting version 3.1.0
