### ISSUE TITLE
Episode length partially incorrect?

### ISSUE THREAD

**Issue by Bench1846** [javikr/sofatime#64]
Hi there! 👋🏼

I was looking for an alternative of TV Time and came across Sofa Time. Trank you so much for this beautiful App - love it!

Now I have to transfer all my data from TV Time and noticed that some of the episode lengths seem to be not correct.

For example: Star Wars: Tales of the Empire.
The Episodes should have a length around 15 Minutes, like it is shown at Trakt.
At Sofa Time all Episodes have a length of 42 minutes.

In total I have a huge difference between Trakt (56 days playtime) and Sofa Time (68 days playtime) for now.

It seems that this only concerns TV Shows, not Films.

There are more examples which i can pick out for you, if you need.

I look forward to further updates and enjoy completing all of my watch history at Sofa Time. 😊

Best regards from Germany! 🙃

**Comment by javikr** [comment]
Hi there!
After comparing the runtime value between TheMovieDB and Trakt for that TV Show (Star Wars: Tales of the Empire), I've seen that the Trakt value is outdated showing 42m for the runtime (https://trakt.tv/shows/star-wars-tales-of-the-empire). I have requested an update. 

Sofa Time takes the runtime from multiple sources including TheMovieDB and Trakt. If TheMovieDB is empty, then it takes from Trakt.

If you find other TV Shows with the same issue, please report them to Trakt (website) using the report button.

Thank you! ;)

**Comment by Bench1846** [comment]
Thank you for your reply. I did not know that there are different "types" of runtime. I only compared the runtime of EACH episode which was different to the "universal" runtime (where you access to), as you can see on the screenshot I made. So I thought it's an issue at Sofa Time. But now I know and where I have to report wrong runtimes (Chucky TV Series is another great example with a runtime of 18h 33m per episode).

![IMG_1364](https://github.com/user-attachments/assets/30e5074b-88f9-4ff1-b408-f87f5bfa81f3)
